Issue #2: Created devcontainer, requirements.txt
ai-cfia/nachet-model pull request #3
Opened 2023-11-14 21:21 UTC by RussellJimmies

#2

2023-11-15 14:46 UTC, rngadam requested changes

2023-11-15 14:46 UTC, rngadam commented on .devcontainer/devcontainer.json
> +			"charliermarsh.ruff",
this is missing new extensions we've decided to standardize on. 

We should move to our own CFIA AI Lab specific extension pack:

https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup

2023-11-15 14:46 UTC, rngadam commented on .devcontainer/devcontainer.json
> +}
EOF linefeed

2023-11-15 20:40 UTC, RussellJimmies commented on .devcontainer/devcontainer.json
> +			"charliermarsh.ruff",
I have all four extensions listed in the Dev Environment Setup Guide for a python project: https://github.com/ai-cfia/dev-rel-docs/blob/main/Development-Environment-Setup-Guide/DEV-ENV-SETUP.md#default-extensions

2023-11-15 20:43 UTC, RussellJimmies commented on .devcontainer/devcontainer.json
> +}
Done

2023-11-16 22:46 UTC, rngadam commented on .devcontainer/devcontainer.json
> +			"charliermarsh.ruff",
I might be confused, I think the new IDE setup changes were actually configuration changes not new extensions, my bad. 

But I still think we should queue up a new issue for creating our own extension pack so we can easily add extensions across.

2023-11-16 22:53 UTC, rngadam approved these changes
What's unclear to me is how this devcontainer will be used and by who?

2023-11-17 16:25 UTC, RussellJimmies commented
I'm about to go develop in this repository

2023-11-17 16:25 UTC, merged