4-create-function-that-generates-a-list-of-dictionaries-containing-model-metadata-from-deployed-endpoints
ai-cfia/nachet-model pull request #5
Opened 2023-11-20 16:01 UTC by RussellJimmies

#4

2023-11-21 21:43 UTC, rngadam requested changes

2023-11-21 21:43 UTC, rngadam commented on models_metadata.py
> +        json.dump(model_endpoints_metadata, outfile)
json.dump(model_endpoints_metadata, outfile, indent=4)

store these json in a nicely formatted json that is human readable.

2023-11-21 21:43 UTC, rngadam commented on .env.template
> +NACHET_WORKSPACE=
https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b

2023-11-21 21:43 UTC, rngadam commented on models_metadata.py
> +            raise Exception("No match found.")
create a custom exception. each layer/module should have its own exception.

2023-11-22 21:21 UTC, RussellJimmies commented on models_metadata.py
> +        json.dump(model_endpoints_metadata, outfile)
Done

2023-11-22 21:21 UTC, RussellJimmies commented on .env.template
> +NACHET_WORKSPACE=
Done

2023-11-22 21:21 UTC, RussellJimmies commented on models_metadata.py
> +            raise Exception("No match found.")
Done

2023-11-22 21:29 UTC, rngadam approved these changes

2023-11-22 21:29 UTC, rngadam commented
added @amirardalan9473 as reviewer

2023-11-29 16:54 UTC, merged